#!/bin/sh

chmod 755 /etc/helium_gateway/install_update
chmod 755 /etc/init.d/helium_gateway
chmod 755 /usr/bin/helium_gateway

chmod 644 /etc/logrotate.d/helium_gateway
chmod 644 /usr/share/syslog-ng/include/tektelic/custom/helium-gateway.conf

#/usr/sbin/update-rc.d helium_gateway defaults 90
#/etc/init.d/helium_gateway restart
